title: Ahmad Saifullah
description: Portfolio & Blog — Software Developer, Trainer, Moslem Preneur, Urban Farmer
url: "https://ahsai.my.id"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /blog/:year/:month/:day/:title/
feed:
  path: /feed.xml
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
